### ISSUE TITLE
怎么计算文本宽度？

### ISSUE THREAD

**Issue by vitasapple** [hon-key/Nudeln#23]
如题，各种字体大小混杂之后，怎么算出最终宽度？

**Comment by hon-key** [comment]
如果只是为了布局view，一般不是固定宽度而高度自适应吗，为什么要算文本高度呢


在2020年08月15日 17:15，vitasapple 写道：

如题，各种字体大小混杂之后，怎么算出最终宽度？

**Comment by vitasapple** [comment]
因为我的文本只有几个字，但是有各种字体大小不一样，还有加粗不加粗这些，然后要在self.view上横向居中，如果不知道宽度，就没法居中，因为渲染出来的Nude是从最左边开始的

> 如果只是为了布局view，一般不是固定宽度而高度自适应吗，为什么要算文本高度呢 在2020年08月15日 17:15，vitasapple 写道： 如题，各种字体大小混杂之后，怎么算出最终宽度？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hon-key** [comment]
一种方法，如果你用autolayout，就可以忽略宽度了，直接把nudein设置为superview的horizental center。如果你不用autolayout，可以在设置完富文本后，使用sizethatfits方法来计算宽度，传入的参数适用cgsizemake（maxfloat，maxfloat）即可




在2020年08月18日 09:43，vitasapple 写道：

因为我的文本只有几个字，但是有各种字体大小不一样，还有加粗不加粗这些，然后要在self.view上横向居中，如果不知道宽度，就没法居中，因为渲染出来的Nude是从最左边开始的

如果只是为了布局view，一般不是固定宽度而高度自适应吗，为什么要算文本高度呢 在2020年08月15日 17:15，vitasapple 写道： 如题，各种字体大小混杂之后，怎么算出最终宽度？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vitasapple** [comment]
> 一种方法，如果你用autolayout，就可以忽略宽度了，直接把nudein设置为superview的horizental center。如果你不用autolayout，可以在设置完富文本后，使用sizethatfits方法来计算宽度，传入的参数适用cgsizemake（maxfloat，maxfloat）即可 在2020年08月18日 09:43，vitasapple 写道： 因为我的文本只有几个字，但是有各种字体大小不一样，还有加粗不加粗这些，然后要在self.view上横向居中，如果不知道宽度，就没法居中，因为渲染出来的Nude是从最左边开始的 如果只是为了布局view，一般不是固定宽度而高度自适应吗，为什么要算文本高度呢 在2020年08月15日 17:15，vitasapple 写道： 如题，各种字体大小混杂之后，怎么算出最终宽度？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的谢谢
